let list =[
    {img:'img_hobby/hobby_pic1.jpg',
    hobby:'学习',
    introduction:"I have my invitation to this world's festival,and thus my life has been blessed.",
    icon:''},
    {img:'img_hobby/hobby_pic2.jpg',
    hobby:'咖啡',
    introduction:"I have my invitation to this world's festival,and thus my life has been blessed.",
    icon:''},
    {img:'img_hobby/hobby_pic3.jpg',
    hobby:'烘焙',
    introduction:"I have my invitation to this world's festival,and thus my life has been blessed.",
    icon:''},
    {img:'img_hobby/hobby_pic4.jpg',
    hobby:'针织',
    introduction:"I have my invitation to this world's festival,and thus my life has been blessed.",
    icon:''},
    {img:'img_hobby/hobby_pic5.jpg',
    hobby:'动漫',
    introduction:"I have my invitation to this world's festival,and thus my life has been blessed.",
    icon:''},
    {img:'img_hobby/hobby_pic6.jpg',
    hobby:'摄影',
    introduction:"I have my invitation to this world's festival,and thus my life has been blessed.",
    icon:''},
    {img:'img_hobby/hobby_pic7.jpg',
    hobby:'集邮',
    introduction:"I have my invitation to this world's festival,and thus my life has been blessed.",
    icon:''},
    {img:'img_hobby/hobby_pic8.jpg',
    hobby:'音乐',
    introduction:"I have my invitation to this world's festival,and thus my life has been blessed.",
    icon:''},
    {img:'img_hobby/hobby_pic9.jpg',
    hobby:'舞蹈',
    introduction:"I have my invitation to this world's festival,and thus my life has been blessed.",
    icon:''},
    {img:'img_hobby/hobby_pic10.jpg',
    hobby:'购物',
    introduction:"I have my invitation to this world's festival,and thus my life has been blessed.",
    icon:''},
]